# Generated by Django 3.0 on 2024-05-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('numero_casa', models.IntegerField()),
                ('placa_veiculo', models.CharField(blank=True, max_length=7)),
                ('foto_morador', models.ImageField(upload_to='imagens/')),
            ],
            options={
                'verbose_name': 'Morador',
                'verbose_name_plural': 'Moradores',
                'db_table': 'morador',
            },
        ),
    ]
