# Generated by Django 3.0 on 2024-03-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='nome_completo',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
    ]
