# Generated by Django 3.0 on 2024-03-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_auto_20240321_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantes',
            name='status',
            field=models.CharField(choices=[('AGURDANDO', 'Agurdando Autorização'), ('EM_VISITA', 'Em visita'), ('FINALIZADO', 'Visita Finalizada')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
    ]
