# Generated by Django 3.0 on 2024-03-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('porteiros', '0002_porteiro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porteiro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuario', verbose_name='usuário'),
        ),
    ]
